server:
  port: 8082
  wait-time-in-ms-when-sync-empty: 3000

spring:
  spring:
    profiles:
      active: native
  data:
      mongodb:
        uri: mongodb://gbLisboa:16833200@127.0.0.1:27017/db_aplicacao?authSource=16833200&retryWrites=true&w=majority
        database: carro
        auto-index-creation: true